/**
 * Demo fixtures for the case library.
 *
 * 11 default tags + 12 anonymized cases that span age bands, severities, and
 * improvement timelines so the counseling search has variety. All before/after
 * URLs are null — we render BackPhotoPlaceholder with a paired severity (high
 * → clear) so the visual story tells itself without real photos.
 *
 * All counseling_comment fields are §4.4.2-compliant (no §8.2 banned words).
 */

import type { CaseRecord, CaseTag } from "./types";
import { demoOrganization } from "@/lib/demo/fixtures";

const ORG = demoOrganization.id;

export const DEMO_CASE_TAGS: CaseTag[] = [
  { id: "tag-inflam",    organizationId: ORG, name: "炎症ニキビ", sortOrder: 10 },
  { id: "tag-pigment",   organizationId: ORG, name: "色素沈着",   sortOrder: 20 },
  { id: "tag-clog",      organizationId: ORG, name: "毛穴詰まり", sortOrder: 30 },
  { id: "tag-dry",       organizationId: ORG, name: "乾燥",       sortOrder: 40 },
  { id: "tag-oily",      organizationId: ORG, name: "皮脂過多",   sortOrder: 50 },
  { id: "tag-redness",   organizationId: ORG, name: "赤み",       sortOrder: 60 },
  { id: "tag-scar",      organizationId: ORG, name: "ニキビ跡",   sortOrder: 70 },
  { id: "tag-itch",      organizationId: ORG, name: "かゆみ",     sortOrder: 80 },
  { id: "tag-sev-heavy", organizationId: ORG, name: "重度",       sortOrder: 100 },
  { id: "tag-sev-med",   organizationId: ORG, name: "中度",       sortOrder: 110 },
  { id: "tag-sev-light", organizationId: ORG, name: "軽度",       sortOrder: 120 },
];

export const DEMO_CASES: CaseRecord[] = [
  {
    id: "case-0001",
    organizationId: ORG,
    anonymousId: "C-0001",
    age: 28,
    gender: "female",
    occupation: "デスクワーク",
    concernDuration: "1〜3年",
    mainConcern: "肩甲骨周りの炎症ニキビと赤み。鏡で見るたび気になっていた。",
    firstVisitDate: "2024-09-10",
    treatmentCount: 6,
    improvementPeriod: "3ヶ月",
    severity: "medium",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "敏感肌寄り。摩擦の少ない衣類への切替を提案。継続意欲高。",
    counselingComment:
      "週1回のサロンケアとホームケアを組み合わせ、3ヶ月で背中のコンディションがすっきり整いました。デスクワーク中心の生活スタイルの方に近い経過です。",
    tagIds: ["tag-inflam", "tag-redness", "tag-sev-med"],
    createdAt: "2024-09-10T09:00:00.000Z",
    updatedAt: "2024-12-10T09:00:00.000Z",
    beforeSeverity: "high",
    afterSeverity: "clear",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
  {
    id: "case-0002",
    organizationId: ORG,
    anonymousId: "C-0002",
    age: 34,
    gender: "female",
    occupation: "営業",
    concernDuration: "3年以上",
    mainConcern: "ニキビ跡と色素沈着。背中の開いた服が着づらかった。",
    firstVisitDate: "2024-05-02",
    treatmentCount: 12,
    improvementPeriod: "6ヶ月",
    severity: "heavy",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "ホルモンバランス起因の可能性。生活リズム改善を併走。",
    counselingComment:
      "長期で取り組んだ事例です。6ヶ月の継続で、トーンの落ち着きと滑らかさが整いました。同じくらいの期間お悩みの方の参考になります。",
    tagIds: ["tag-scar", "tag-pigment", "tag-sev-heavy"],
    createdAt: "2024-05-02T09:00:00.000Z",
    updatedAt: "2024-11-02T09:00:00.000Z",
    beforeSeverity: "high",
    afterSeverity: "low",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
  {
    id: "case-0003",
    organizationId: ORG,
    anonymousId: "C-0003",
    age: 22,
    gender: "female",
    occupation: "学生",
    concernDuration: "半年〜1年",
    mainConcern: "皮脂過多と毛穴詰まり。汗をかきやすい体質。",
    firstVisitDate: "2024-11-15",
    treatmentCount: 4,
    improvementPeriod: "2ヶ月",
    severity: "light",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "若年層・運動部。シャワー習慣のアドバイスが効いた。",
    counselingComment:
      "若い世代で皮脂が気になる方の事例です。2ヶ月という比較的短い期間で、肌コンディションが安定する経過になりました。",
    tagIds: ["tag-oily", "tag-clog", "tag-sev-light"],
    createdAt: "2024-11-15T09:00:00.000Z",
    updatedAt: "2025-01-15T09:00:00.000Z",
    beforeSeverity: "medium",
    afterSeverity: "clear",
    beforeLighting: "warm",
    afterLighting: "warm",
  },
  {
    id: "case-0004",
    organizationId: ORG,
    anonymousId: "C-0004",
    age: 42,
    gender: "female",
    occupation: "経営者",
    concernDuration: "3年以上",
    mainConcern: "乾燥とかゆみ。冬場に悪化しやすい。",
    firstVisitDate: "2024-03-20",
    treatmentCount: 18,
    improvementPeriod: "9ヶ月",
    severity: "medium",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "ストレス由来も併発。リラックス目的の継続を希望。",
    counselingComment:
      "40代で乾燥が中心の方の事例です。9ヶ月の継続で、季節の変わり目でも安定したコンディションを保てるようになりました。",
    tagIds: ["tag-dry", "tag-itch", "tag-sev-med"],
    createdAt: "2024-03-20T09:00:00.000Z",
    updatedAt: "2024-12-20T09:00:00.000Z",
    beforeSeverity: "high",
    afterSeverity: "low",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
  {
    id: "case-0005",
    organizationId: ORG,
    anonymousId: "C-0005",
    age: 31,
    gender: "female",
    occupation: "看護師",
    concernDuration: "1〜3年",
    mainConcern: "夜勤後のニキビと赤みが繰り返し出ていた。",
    firstVisitDate: "2024-08-05",
    treatmentCount: 8,
    improvementPeriod: "6ヶ月",
    severity: "heavy",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "不規則勤務。睡眠リズム前提のホームケア設計を共有。",
    counselingComment:
      "夜勤のあるお仕事の方の事例です。生活リズムに合わせたホームケアを組み合わせて、半年でコンディションが整いました。",
    tagIds: ["tag-inflam", "tag-redness", "tag-sev-heavy"],
    createdAt: "2024-08-05T09:00:00.000Z",
    updatedAt: "2025-02-05T09:00:00.000Z",
    beforeSeverity: "high",
    afterSeverity: "low",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
  {
    id: "case-0006",
    organizationId: ORG,
    anonymousId: "C-0006",
    age: 26,
    gender: "female",
    occupation: "美容師",
    concernDuration: "半年〜1年",
    mainConcern: "毛穴詰まりと小さなプツプツ。背中の開きデザインを着たい。",
    firstVisitDate: "2024-10-01",
    treatmentCount: 6,
    improvementPeriod: "3ヶ月",
    severity: "light",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "美容意識高い。週次ホームケアの定着が早かった。",
    counselingComment:
      "20代後半・短期間で結果を求める方の事例です。3ヶ月でコンディションが整い、ご希望のお洋服を楽しめるようになりました。",
    tagIds: ["tag-clog", "tag-sev-light"],
    createdAt: "2024-10-01T09:00:00.000Z",
    updatedAt: "2025-01-01T09:00:00.000Z",
    beforeSeverity: "medium",
    afterSeverity: "clear",
    beforeLighting: "warm",
    afterLighting: "warm",
  },
  {
    id: "case-0007",
    organizationId: ORG,
    anonymousId: "C-0007",
    age: 47,
    gender: "female",
    occupation: "主婦",
    concernDuration: "3年以上",
    mainConcern: "色素沈着と凹凸感。露出のある服を避けていた。",
    firstVisitDate: "2023-12-10",
    treatmentCount: 24,
    improvementPeriod: "12ヶ月以上",
    severity: "heavy",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "長期コミット。年単位の経過を許容できる方向き。",
    counselingComment:
      "40代後半・長期じっくり型の事例です。1年以上の継続で、トーンと質感の両方に変化が出てきました。",
    tagIds: ["tag-pigment", "tag-scar", "tag-sev-heavy"],
    createdAt: "2023-12-10T09:00:00.000Z",
    updatedAt: "2024-12-10T09:00:00.000Z",
    beforeSeverity: "high",
    afterSeverity: "low",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
  {
    id: "case-0008",
    organizationId: ORG,
    anonymousId: "C-0008",
    age: 29,
    gender: "female",
    occupation: "ヨガインストラクター",
    concernDuration: "半年〜1年",
    mainConcern: "汗による赤みとかゆみが気になっていた。",
    firstVisitDate: "2024-09-25",
    treatmentCount: 6,
    improvementPeriod: "3ヶ月",
    severity: "medium",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "アクティブ系。施術後の保湿継続が肝。",
    counselingComment:
      "汗をかきやすいライフスタイルの方の事例です。3ヶ月でかゆみや赤みが落ち着き、活動への集中度が上がりました。",
    tagIds: ["tag-redness", "tag-itch", "tag-sev-med"],
    createdAt: "2024-09-25T09:00:00.000Z",
    updatedAt: "2024-12-25T09:00:00.000Z",
    beforeSeverity: "medium",
    afterSeverity: "clear",
    beforeLighting: "warm",
    afterLighting: "warm",
  },
  {
    id: "case-0009",
    organizationId: ORG,
    anonymousId: "C-0009",
    age: 38,
    gender: "female",
    occupation: "事務職",
    concernDuration: "1〜3年",
    mainConcern: "ニキビ跡が残りやすく、メイクや衣類で隠していた。",
    firstVisitDate: "2024-06-15",
    treatmentCount: 12,
    improvementPeriod: "6ヶ月",
    severity: "medium",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "30代後半。週1ペースでの来店が定着。",
    counselingComment:
      "30代後半でニキビ跡が気になる方の事例です。6ヶ月の継続で、お肌のトーンがなめらかに整いました。",
    tagIds: ["tag-scar", "tag-pigment", "tag-sev-med"],
    createdAt: "2024-06-15T09:00:00.000Z",
    updatedAt: "2024-12-15T09:00:00.000Z",
    beforeSeverity: "high",
    afterSeverity: "low",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
  {
    id: "case-0010",
    organizationId: ORG,
    anonymousId: "C-0010",
    age: 24,
    gender: "female",
    occupation: "アパレル",
    concernDuration: "半年〜1年",
    mainConcern: "炎症ニキビが頻発し、自信を失っていた。",
    firstVisitDate: "2024-11-01",
    treatmentCount: 5,
    improvementPeriod: "2ヶ月",
    severity: "medium",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "シャワー後のケアが乱れがち。短時間ルーティンを提案。",
    counselingComment:
      "20代前半で炎症が気になる方の事例です。短期集中で2ヶ月、肌の落ち着きを実感していただけました。",
    tagIds: ["tag-inflam", "tag-redness", "tag-sev-med"],
    createdAt: "2024-11-01T09:00:00.000Z",
    updatedAt: "2025-01-01T09:00:00.000Z",
    beforeSeverity: "high",
    afterSeverity: "low",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
  {
    id: "case-0011",
    organizationId: ORG,
    anonymousId: "C-0011",
    age: 51,
    gender: "female",
    occupation: "公務員",
    concernDuration: "3年以上",
    mainConcern: "乾燥による粉ふきとかゆみが慢性的にあった。",
    firstVisitDate: "2024-04-12",
    treatmentCount: 16,
    improvementPeriod: "9ヶ月",
    severity: "medium",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "更年期世代。サロン+ホームケア両輪で着実な経過。",
    counselingComment:
      "50代で乾燥にお悩みの方の事例です。9ヶ月の継続で、季節を問わず落ち着いた状態を保てるようになりました。",
    tagIds: ["tag-dry", "tag-itch", "tag-sev-med"],
    createdAt: "2024-04-12T09:00:00.000Z",
    updatedAt: "2025-01-12T09:00:00.000Z",
    beforeSeverity: "medium",
    afterSeverity: "clear",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
  {
    id: "case-0012",
    organizationId: ORG,
    anonymousId: "C-0012",
    age: 33,
    gender: "female",
    occupation: "Webディレクター",
    concernDuration: "1〜3年",
    mainConcern: "ストレス時期に炎症が悪化。継続して整えたい。",
    firstVisitDate: "2024-07-20",
    treatmentCount: 10,
    improvementPeriod: "6ヶ月",
    severity: "heavy",
    beforeImageUrl: null,
    afterImageUrl: null,
    staffMemo: "リモートワーク中心。デスク周辺の姿勢提案も併走。",
    counselingComment:
      "30代でストレス由来の悪化を繰り返していた方の事例です。6ヶ月の伴走で、波の少ない安定した状態に近づきました。",
    tagIds: ["tag-inflam", "tag-scar", "tag-sev-heavy"],
    createdAt: "2024-07-20T09:00:00.000Z",
    updatedAt: "2025-01-20T09:00:00.000Z",
    beforeSeverity: "high",
    afterSeverity: "low",
    beforeLighting: "cool",
    afterLighting: "warm",
  },
];
